### ISSUE TITLE
New Zealand Government open data portal

### ISSUE THREAD

**Issue by melessawy** [okfn/dataportals.org#228] opened 2021-10-30 08:04 UTC
`* Required`

# Key Data Portal Information
---
## Description *

# Additional Information
## Full metadata download

# Your Information
## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by augusto-herrmann** [comment] 2021-11-04 03:06
Thanks for the submission, @melessawy. However, without filling in the required fields on the template above, we cannot act on it. Please edit, review and fill all of the required fields.

**Comment by augusto-herrmann** [comment] 2021-12-12 15:37
The required information fields were left empty. This also might be a duplicate of  the `open_org_nz` entry.

So I'm closing this issue. If you have the required information, feel free to fill them in and reopen.

**Closed by augusto-herrmann** 2021-12-12 15:37 UTC
Labels: duplicate, invalid
