### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by grhammo** [okfn/dataportals.org#58] opened 2015-09-15 00:39 UTC
Can a search functionality to be added to this list please? I would like to search by Australia, but am unable to do so.

**Comment by Stephen-Gates** [comment] 2015-09-15 01:16
Search does exist on the home page but it would be nice if it was available across the site or at least on the [Browse page](http://dataportals.org/search)

**Comment by rgrp** [comment] 2015-11-18 13:45
DUPLICATE of #42 IMO

**Closed by rgrp** 2015-11-18 13:45 UTC
